//
//  Icons.swift
//  DailyGo
//
//  Created by Danila Petrov on 25.03.2025.
//

import UIKit 

public enum Icons {
    public static let whiteBullet_5 = UIImage(named: "white_bullet_5")
    public static let otherPage_5 = UIImage(named: "other_page_5")
    public static let currentPage_5 = UIImage(named: "current_page_5")

    public static let addCircle_10 = UIImage(named: "add_circle_10")
    public static let checkCircle_10 = UIImage(named: "check_circle_10")
    public static let enterteinment_10 = UIImage(named: "enterteinment_10")
    public static let settingsMenu_10 = UIImage(named: "settings_menu_10")
    public static let whiteBullet_10 = UIImage(named: "white_bullet_10")
    public static let whiteCircle_10 = UIImage(named: "white_circle_10")

    public static let add_15 = UIImage(named: "add_15")
    public static let check_15 = UIImage(named: "check_15")
    public static let chevronLeft_15 = UIImage(named: "chevron_left_15")
    public static let chevronRight_15 = UIImage(named: "chevron_right_15")
    public static let delete_15 = UIImage(named: "delete_15")
    public static let deleteBin_15 = UIImage(named: "delete_bin_15")
    public static let editWrite_15 = UIImage(named: "edit_write_15")

    public static let bellNotify_20 = UIImage(named: "bell_notify_20")
    public static let bookPen_20 = UIImage(named: "book_pen_20")
    public static let calendar_20 = UIImage(named: "calendar_20")
    public static let deleteBin_20 = UIImage(named: "delete_bin_20")
    public static let documentFile_20 = UIImage(named: "document_file_20")
    public static let flag_20 = UIImage(named: "flag_20")
    public static let heartPulse_20 = UIImage(named: "heart_pulse_20")
    public static let refreshArrow_20 = UIImage(named: "refresh_arrow_20")
    public static let menuHamburger_20 = UIImage(named: "menu_hamburger_20")
    public static let scissorsTool_20 = UIImage(named: "scissors_tool_20")
    public static let searchMagnify_20 = UIImage(named: "search_magnify_20")
    public static let squareShape_20 = UIImage(named: "square_shape_20")

    public static let checkCircle_25 = UIImage(named: "check_circle_25")
    public static let enterneinment_25 = UIImage(named: "enterneinment_25")
    public static let settingsMenu_25 = UIImage(named: "settings_menu_25")
    public static let image_25 = UIImage(named: "image_25")
    public static let whiteCircle_25 = UIImage(named: "white_circle_25")

    public static let airplane_30 = UIImage(named: "airplane_30")
    public static let balanceScale_30 = UIImage(named: "balance_scale_30")
    public static let beach_30 = UIImage(named: "beach_30")
    public static let binocular_30 = UIImage(named: "binocular_30")
    public static let booksLibrary_30 = UIImage(named: "books_library_30")
    public static let car_30 = UIImage(named: "car_30")
    public static let computerScreen_30 = UIImage(named: "computer_screen_30")
    public static let crown_30 = UIImage(named: "crown_30")
    public static let dogHead_30 = UIImage(named: "dog_head_30")
    public static let drinkBeer_30 = UIImage(named: "drink_beer_30")
    public static let drinkCocktail_30 = UIImage(named: "drink_cocktail_30")
    public static let drinkCupTea_30 = UIImage(named: "drink_cup_tea_30")
    public static let dumbbell_30 = UIImage(named: "dumbbell_30")
    public static let editBrush_30 = UIImage(named: "edit_brush_30")
    public static let earpods_30 = UIImage(named: "earpods_30")
    public static let editPaint_30 = UIImage(named: "edit_paint_30")
    public static let flower_30 = UIImage(named: "flower_30")
    public static let flowerLotus_30 = UIImage(named: "flower_lotus_30")
    public static let flowerRose_30 = UIImage(named: "flower_rose_30")
    public static let foodCake_30 = UIImage(named: "food_cake_30")
    public static let foodFish_30 = UIImage(named: "food_fish_30")
    public static let foodKitchen_30 = UIImage(named: "food_kitchen_30")
    public static let foodMelon_30 = UIImage(named: "food_melon_30")
    public static let foodPopcorn_30 = UIImage(named: "food_popcorn_30")
    public static let giftReward_30 = UIImage(named: "gift_reward_30")
    public static let globe_30 = UIImage(named: "globe_30")
    public static let heart_30 = UIImage(named: "heart_30")
    public static let help_30 = UIImage(named: "help_30")
    public static let house_30 = UIImage(named: "house_30")
    public static let mask_30 = UIImage(named: "mask_30")
    public static let moneyBank_30 = UIImage(named: "money_bank_30")
    public static let mountain_30 = UIImage(named: "mountain_30")
    public static let moon_30 = UIImage(named: "moon_30")
    public static let party_30 = UIImage(named: "party_30")
    public static let petPaw_30 = UIImage(named: "pet_paw_30")
    public static let pottedTree_30 = UIImage(named: "potted_tree_30")
    public static let puzzle_30 = UIImage(named: "puzzle_30")
    public static let poolStairs_30 = UIImage(named: "pool_stairs_30")
    public static let screwdriver_30 = UIImage(named: "screwdriver_30")
    public static let rainbow_30 = UIImage(named: "rainbow_30")
    public static let snowFlake_30 = UIImage(named: "snow_flake_30")
    public static let sun_30 = UIImage(named: "sun_30")
    public static let tShirt_30 = UIImage(named: "t_shirt_30")
    public static let sunRise_30 = UIImage(named: "sun_rise_30")
    public static let toolBox_30 = UIImage(named: "tool_box_30")
    public static let weatherCloud_30 = UIImage(named: "weather_cloud_30")
    public static let userMultiple_30 = UIImage(named: "user_multiple_30")
    public static let weatherLightning_30 = UIImage(named: "weather_lightning_30")
    public static let trophy_30 = UIImage(named: "trophy_30")
    public static let weatherRain_30 = UIImage(named: "weather_rain_30")
    public static let weatherSnow_30 = UIImage(named: "weather_snow_30")
    public static let youtube_30 = UIImage(named: "youtube_30")
    public static let cashBag_30 = UIImage(named: "cash_bag_30")
    public static let catHead_30 = UIImage(named: "cat_head_30")

    public static let addCircle_35 = UIImage(named: "add_circle_35")
    public static let deleteCircle_35 = UIImage(named: "delete_circle_35")

    public static let angryFrown_40 = UIImage(named: "angry_frown_40")
    public static let annoyedAngry_40 = UIImage(named: "annoyed_angry_40")
    public static let confusedShocked_40 = UIImage(named: "confused_shocked_40")
    public static let cryingSad_40 = UIImage(named: "crying_sad_40")
    public static let excitedSquinting_40 = UIImage(named: "excited_squinting_40")
    public static let happyCalm_40 = UIImage(named: "happy_calm_40")
    public static let happyCheerful_40 = UIImage(named: "happy_cheerful_40")
    public static let happyContent_40 = UIImage(named: "happy_content_40")
    public static let happySmiling_40 = UIImage(named: "happy_smiling_40")
    public static let happyUpsideDown_40 = UIImage(named: "happy_upside_down_40")
    public static let loveExcited_40 = UIImage(named: "love_excited_40")
    public static let nervousWavy_40 = UIImage(named: "nervous_wavy_40")
    public static let loveHappy_40 = UIImage(named: "love_happy_40")
    public static let neutralCalm_40 = UIImage(named: "neutral_calm_40")
    public static let neutralBlank_40 = UIImage(named: "neutral_blank_40")
    public static let neutralConfused_40 = UIImage(named: "neutral_confused_40")
    public static let neutralFlat_40 = UIImage(named: "neutral_flat_40")
    public static let neutralFriendly_40 = UIImage(named: "neutral_friendly_40")
    public static let neutralStraight_40 = UIImage(named: "neutral_straight_40")
    public static let neutralPlain_40 = UIImage(named: "neutral_plain_40")
    public static let neutralUnsure_40 = UIImage(named: "neutral_unsure_40")
    public static let peacefulSleepy_40 = UIImage(named: "peaceful_sleepy_40")
    public static let peacefulResting_40 = UIImage(named: "peaceful_resting_40")
    public static let sadCheerful_40 = UIImage(named: "sad_cheerful_40")
    public static let sadFrown_40 = UIImage(named: "sad_frown_40")
    public static let sadUnhappy_40 = UIImage(named: "sad_unhappy_40")
    public static let sadDisappointed_40 = UIImage(named: "sad_disappointed_40")
    public static let sleepyYawning_40 = UIImage(named: "sleepy_yawning_40")
    public static let sleepyTired_40 = UIImage(named: "sleepy_tired_40")
    public static let smirkRelaxed_40 = UIImage(named: "smirk_relaxed_40")
    public static let surprisedWideEyes_40 = UIImage(named: "surprised_wide_eyes_40")
    public static let surprisedShocked_40 = UIImage(named: "surprised_shocked_40")
}
