//
//  Icons.swift
//  DailyGo
//
//  Created by Danila Petrov on 25.03.2025.
//

import UIKit 

public enum Icons {
    public static let whiteBullet_5 = getImage(name: "white_bullet_5")
    public static let otherPage_5 = getImage(name: "other_page_5")
    public static let currentPage_5 = getImage(name: "current_page_5")

    public static let addCircle_10 = getImage(name: "add_circle_10")
    public static let checkCircle_10 = getImage(name: "check_circle_10")
    public static let enterteinment_10 = getImage(name: "enterteinment_10")
    public static let settingsMenu_10 = getImage(name: "settings_menu_10")
    public static let whiteBullet_10 = getImage(name: "white_bullet_10")
    public static let whiteCircle_10 = getImage(name: "white_circle_10")

    public static let add_15 = getImage(name: "add_15")
    public static let check_15 = getImage(name: "check_15")
    public static let chevronLeft_15 = getImage(name: "chevron_left_15")
    public static let chevronRight_15 = getImage(name: "chevron_right_15")
    public static let delete_15 = getImage(name: "delete_15")
    public static let deleteBin_15 = getImage(name: "delete_bin_15")
    public static let editWrite_15 = getImage(name: "edit_write_15")

    public static let bellNotify_20 = getImage(name: "bell_notify_20")
    public static let bookPen_20 = getImage(name: "book_pen_20")
    public static let calendar_20 = getImage(name: "calendar_20")
    public static let deleteBin_20 = getImage(name: "delete_bin_20")
    public static let documentFile_20 = getImage(name: "document_file_20")
    public static let flag_20 = getImage(name: "flag_20")
    public static let heartPulse_20 = getImage(name: "heart_pulse_20")
    public static let refreshArrow_20 = getImage(name: "refresh_arrow_20")
    public static let menuHamburger_20 = getImage(name: "menu_hamburger_20")
    public static let scissorsTool_20 = getImage(name: "scissors_tool_20")
    public static let searchMagnify_20 = getImage(name: "search_magnify_20")
    public static let squareShape_20 = getImage(name: "square_shape_20")

    public static let checkCircle_25 = getImage(name: "check_circle_25")
    public static let enterneinment_25 = getImage(name: "enterneinment_25")
    public static let settingsMenu_25 = getImage(name: "settings_menu_25")
    public static let image_25 = getImage(name: "image_25")
    public static let whiteCircle_25 = getImage(name: "white_circle_25")
    public static let appstore_25 = getImage(name: "appstore_25")
    public static let calendar_25 = getImage(name: "calendar_25")
    public static let diary_25 = getImage(name: "diary_25")
    public static let events_25 = getImage(name: "events_25")
    public static let facebook_25 = getImage(name: "facebook_25")
    public static let habitFormation_25 = getImage(name: "habit_formation_25")
    public static let habits_25 = getImage(name: "habits_25")
    public static let improveMood_25 = getImage(name: "improve_mood_25")
    public static let incrProductivity_25 = getImage(name: "incr_productivity_25")
    public static let instagram_25 = getImage(name: "instagram_25")
    public static let mood_25 = getImage(name: "mood_25")
    public static let otherMessengers_25 = getImage(name: "other_messengers_25")
    public static let selfReflGrowth_25 = getImage(name: "self_refl_growth_25")
    public static let tasks_25 = getImage(name: "tasks_25")
    public static let tikTok_25 = getImage(name: "tikTok_25")
    public static let timeManagement_25 = getImage(name: "time_management_25")
    public static let toDoList_25 = getImage(name: "to_do_list_25")

    public static let airplane_30 = getImage(name: "airplane_30")
    public static let balanceScale_30 = getImage(name: "balance_scale_30")
    public static let beach_30 = getImage(name: "beach_30")
    public static let binocular_30 = getImage(name: "binocular_30")
    public static let booksLibrary_30 = getImage(name: "books_library_30")
    public static let car_30 = getImage(name: "car_30")
    public static let computerScreen_30 = getImage(name: "computer_screen_30")
    public static let crown_30 = getImage(name: "crown_30")
    public static let dogHead_30 = getImage(name: "dog_head_30")
    public static let drinkBeer_30 = getImage(name: "drink_beer_30")
    public static let drinkCocktail_30 = getImage(name: "drink_cocktail_30")
    public static let drinkCupTea_30 = getImage(name: "drink_cup_tea_30")
    public static let dumbbell_30 = getImage(name: "dumbbell_30")
    public static let editBrush_30 = getImage(name: "edit_brush_30")
    public static let earpods_30 = getImage(name: "earpods_30")
    public static let editPaint_30 = getImage(name: "edit_paint_30")
    public static let flower_30 = getImage(name: "flower_30")
    public static let flowerLotus_30 = getImage(name: "flower_lotus_30")
    public static let flowerRose_30 = getImage(name: "flower_rose_30")
    public static let foodCake_30 = getImage(name: "food_cake_30")
    public static let foodFish_30 = getImage(name: "food_fish_30")
    public static let foodKitchen_30 = getImage(name: "food_kitchen_30")
    public static let foodMelon_30 = getImage(name: "food_melon_30")
    public static let foodPopcorn_30 = getImage(name: "food_popcorn_30")
    public static let giftReward_30 = getImage(name: "gift_reward_30")
    public static let globe_30 = getImage(name: "globe_30")
    public static let heart_30 = getImage(name: "heart_30")
    public static let help_30 = getImage(name: "help_30")
    public static let house_30 = getImage(name: "house_30")
    public static let mask_30 = getImage(name: "mask_30")
    public static let moneyBank_30 = getImage(name: "money_bank_30")
    public static let mountain_30 = getImage(name: "mountain_30")
    public static let moon_30 = getImage(name: "moon_30")
    public static let party_30 = getImage(name: "party_30")
    public static let petPaw_30 = getImage(name: "pet_paw_30")
    public static let pottedTree_30 = getImage(name: "potted_tree_30")
    public static let puzzle_30 = getImage(name: "puzzle_30")
    public static let poolStairs_30 = getImage(name: "pool_stairs_30")
    public static let screwdriver_30 = getImage(name: "screwdriver_30")
    public static let rainbow_30 = getImage(name: "rainbow_30")
    public static let snowFlake_30 = getImage(name: "snow_flake_30")
    public static let sun_30 = getImage(name: "sun_30")
    public static let tShirt_30 = getImage(name: "t_shirt_30")
    public static let sunRise_30 = getImage(name: "sun_rise_30")
    public static let toolBox_30 = getImage(name: "tool_box_30")
    public static let weatherCloud_30 = getImage(name: "weather_cloud_30")
    public static let userMultiple_30 = getImage(name: "user_multiple_30")
    public static let weatherLightning_30 = getImage(name: "weather_lightning_30")
    public static let trophy_30 = getImage(name: "trophy_30")
    public static let weatherRain_30 = getImage(name: "weather_rain_30")
    public static let weatherSnow_30 = getImage(name: "weather_snow_30")
    public static let youtube_30 = getImage(name: "youtube_30")
    public static let cashBag_30 = getImage(name: "cash_bag_30")
    public static let catHead_30 = getImage(name: "cat_head_30")

    public static let addCircle_35 = getImage(name: "add_circle_35")
    public static let deleteCircle_35 = getImage(name: "delete_circle_35")

    public static let angryFrown_40 = getImage(name: "angry_frown_40")
    public static let annoyedAngry_40 = getImage(name: "annoyed_angry_40")
    public static let confusedShocked_40 = getImage(name: "confused_shocked_40")
    public static let cryingSad_40 = getImage(name: "crying_sad_40")
    public static let excitedSquinting_40 = getImage(name: "excited_squinting_40")
    public static let happyCalm_40 = getImage(name: "happy_calm_40")
    public static let happyCheerful_40 = getImage(name: "happy_cheerful_40")
    public static let happyContent_40 = getImage(name: "happy_content_40")
    public static let happySmiling_40 = getImage(name: "happy_smiling_40")
    public static let happyUpsideDown_40 = getImage(name: "happy_upside_down_40")
    public static let loveExcited_40 = getImage(name: "love_excited_40")
    public static let nervousWavy_40 = getImage(name: "nervous_wavy_40")
    public static let loveHappy_40 = getImage(name: "love_happy_40")
    public static let neutralCalm_40 = getImage(name: "neutral_calm_40")
    public static let neutralBlank_40 = getImage(name: "neutral_blank_40")
    public static let neutralConfused_40 = getImage(name: "neutral_confused_40")
    public static let neutralFlat_40 = getImage(name: "neutral_flat_40")
    public static let neutralFriendly_40 = getImage(name: "neutral_friendly_40")
    public static let neutralStraight_40 = getImage(name: "neutral_straight_40")
    public static let neutralPlain_40 = getImage(name: "neutral_plain_40")
    public static let neutralUnsure_40 = getImage(name: "neutral_unsure_40")
    public static let peacefulSleepy_40 = getImage(name: "peaceful_sleepy_40")
    public static let peacefulResting_40 = getImage(name: "peaceful_resting_40")
    public static let sadCheerful_40 = getImage(name: "sad_cheerful_40")
    public static let sadFrown_40 = getImage(name: "sad_frown_40")
    public static let sadUnhappy_40 = getImage(name: "sad_unhappy_40")
    public static let sadDisappointed_40 = getImage(name: "sad_disappointed_40")
    public static let sleepyYawning_40 = getImage(name: "sleepy_yawning_40")
    public static let sleepyTired_40 = getImage(name: "sleepy_tired_40")
    public static let smirkRelaxed_40 = getImage(name: "smirk_relaxed_40")
    public static let surprisedWideEyes_40 = getImage(name: "surprised_wide_eyes_40")
    public static let surprisedShocked_40 = getImage(name: "surprised_shocked_40")

    public static let logo = getImage(name: "logo")
}

private extension Icons {

    static func getImage(name: String) -> UIImage {
        return UIImage(named: name)!
    }
}
